# Site metadata
title: Zac Gwennap Portfolio
description: Explore my personal portfolio showcasing projects, skills, and professional experience. Built with Just the Docs and GitHub Pages.
remote_theme: just-the-docs/just-the-docs

# Site URL
url: https://zacgwennap.github.io

# Auxiliary links (if needed)
aux_links:
  GitHub: https://github.com/zacgwennap
  LinkedIn: https://www.linkedin.com/in/zachary-gwennap/

markdown: kramdown
kramdown:
  math_engine: mathjax


defaults:
  -
    scope:
      path: ""
    values:
      includes:
        - mathjax
