# Site metadata
title: Zac Gwennap Portfolio
description: Explore my personal portfolio showcasing projects, skills, and professional experience. Built with Just the Docs and GitHub Pages.
theme: just-the-docs

# Site URL
url: https://ZacCac.github.io

# Auxiliary links (if needed)
aux_links:
  GitHub Repository: https://github.com/ZacCac/ZacCac.github.io
  LinkedIn: https://www.linkedin.com/in/zacgwennap/
